version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_API_SERVER=${REACT_APP_BASE_API_SERVER:-https://dxhp0j33db.execute-api.us-east-1.amazonaws.com/dev}
      - REACT_APP_AUTH0_DOMAIN=${REACT_APP_AUTH0_DOMAIN:-dev-oml3gexqytc7oo2l.us.auth0.com}
      - REACT_APP_AUTH0_CLIENT_ID=${REACT_APP_AUTH0_CLIENT_ID:-6satcFsIaqEedHaMNO65bGZ61TdjcqlB}
      - REACT_APP_AUTH0_REDIRECT_URI=${REACT_APP_AUTH0_REDIRECT_URI:-http://localhost:3000}
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true